name: EssentialsJC
version: '${project.version}'
main: com.jeancalistro.essentials.EssentialJC
api-version: '1.20'
commands:
  fix:
    usage: /fix
  ping:
    usage: /ping
  setwarp:
    usage: /setwarp <warp name>
  warp:
    usage: /warp <warp>
  delwarp:
    usage: /delwarp <warp>